## El momento histórico

Category: [El momento histórico](http://descubrircorrientes.com.ar/2012/index.php/479-historia-desde-el-origen-hasta-1814/tierra-argentina-1492-1588/la-aventura-del-rio-de-la-plata/americo-vespucio-descubridor-del-rio-de-la-plata/la-monarquia-bicefala-de-los-reyes-catolicos/el-momento-historico)

Los navegantes hicieron posible el conocimiento de regiones separadas de Europa por un océano en el que, se presumía, de acuerdo a generalizadas teorías, que terminaba el plano de la tierra y se abría un abismo incomprensible. El Descubrimiento del Nuevo Mundo se llevó a cabo bajo contradicciones y malentendidos. Así nació América<sub><strong>(1)</strong></sub>.

## **(1)** Material extraído del libro "Los hombres que gobernaron Corrientes (compendio de historia política)", de Gabriel Enrique del Valle.

El nombre con que se la designó durante mucho tiempo, Indias, no hizo más que perpetuar el error de Cristóbal Colón, quien había salido en busca de las Indias Orientales por el Occidente y, cumpliendo esta misión, no quiso admitir que estaba en presencia de un continente desconocido hasta entonces. Se ha dicho con razón que fue un descubridor a pesar suyo.  

Tenía que satisfacer el compromiso económico contraido, más importante que el descubrir unas islas pobladas de salvajes: su objetivo era ir en busca de especias directamente a los países que las producían, por una ruta marítima más corta que la del Cabo. Las caravanas no podían usar los caminos en Asia, interrumpidos como consecuencia de la toma de Constantinopla por los turcos.

Muchos de los marinos que formaban la tripulación de las naves entre el Viejo y el Nuevo Mundo se convirtieron en conquistadores; tal vez lo esencial de las tripulaciones estaba constituido por conquistadores, marineros por necesidad, que contaban con la asistencia de un pequeño número de verdaderos hombres de mar, pilotos, timoneles, expertos en navegación costera de bajo calado.

Las expediciones eran cosmopolitas. Colón, Caboto y Vespucio, por ejemplo, navegaban a beneficio de quien quisiera ayudarlos. La posibilidad de hacer fortuna en esas largas e impredecibles travesías, atraía también a otros marineros europeos.

Los artesanos, capaces de calafatear las brechas en el casco de un navío, eran con frecuencia griegos, nombre que comprendía también a los malteses y a los nativos del Cercano Oriente.

Dichos antecedentes hacen precisar que el descubrimiento de América no fue tal. Sólo hubo conquistas en regiones alejadas unas de otras que, poco a poco, fueron revelándose como partes del gran conjunto geográfico que comprendía un inmenso continente.

Las conquistas fueron realizadas, en su mayor parte, dentro del marco jurídico que les otorgaba la Monarquía española, factor de unidad bastante frágil, ya que la Corona de España existía desde pocos años antes, exactamente desde 1479, cuando se celebró el matrimonio de Fernando de Aragón y de Isabel de Castilla.

Pero la Monarquía española no actuaba como potencia conquistadora; los particulares organizaban expediciones de conquista por cuenta propia y pedían a los soberanos de Aragón y Castilla una caución jurídica que serviría para distinguir a los conquistadores de los simples piratas.

Se seguiría llamando “indios” a los naturales, e “indianos” a los españoles instalados en el Nuevo Mundo en los siglos XVI y XVII. Geógrafos como Waldseemüller lanzaron muy pronto el nombre de “terra America” en honor de Américo Vespucio, que fue el primero en reconocer la costa oriental de la América meridional. Pero el nombre de “Indias” fue empleado siempre para designar lo que ahora llamamos América.

El historiador francés Jacques Lafaye señala en su libro “Los Conquistadores” que

“lo que dio nacimiento a América, en cuanto espacio geográficamente limitado, entidad consciente de sí misma y sobre todo entidad en la conciencia de los europeos, en una palabra, realidad geopolítica, fue la colonización hispano-portuguesa, que confirió al Nuevo Mundo la unidad religiosa, administrativa, en parte lingüística y, sobre todo, política. La unidad espiritual de los conquistadores se va a prolongar -y a transformar-, en la de los criollos, quienes consideran su país como un ‘paraíso occidental’, según la expresión de un erudito mexicano del siglo XVII, don Carlos de Sigüenza y Góngora”.

Las conquistas eran expediciones privadas. Desde un punto de vista económico, las expediciones se fundaban en el contrato entre un capitán (un hidalgo) y comerciantes o banqueros, por lo general algún armador. Estos adelantaban los fondos necesarios o suministraban los barcos, las provisiones, las municiones y los elementos de pacotilla para los trueques.

El capitán se comprometía a compartir el botín con sus comanditarios. Debía dirigir a la expedición y previamente reclutar los miembros entre caballeros -los que tenían un caballo-, y peones. El caballo, extraño a la fauna del Nuevo Mundo, alcanzó rápidamente precios elevados.

El riesgo económico sólo afectaba a los particulares: los reyes intervenían exclusivamente como parte recibidora, por lo que toda expedición llevaba un controlador de las finanzas, contador, encargado de velar por el quinto, es decir el descuento de la quinta parte del botín destinada al Tesoro Real, que se depositaba en la Torre del Oro de la ciudad de Sevilla.

El antecedente inmediato de la conquista americana fue la guerra contra los moros. Francisco López de Gómara, intérprete de las reivindicaciones de los conquistadores, escribió que

“comenzaron las conquistas de indios acabada la de los moros, porque siempre guerrearon españoles contra infieles”.

El fin perseguido por los conquistadores era la solicitud de las dos mercedes habituales que otorgaba la Corona: la encomienda de tierras y el título de nobleza que pudiera corresponderles.

La conquista fue más fácil donde existían Imperios sólidamente constituidos (aztecas, mayas, incas -es decir, México y Perú-) que en aquellas zonas habitadas por tribus poco desarrolladas culturalmente. Tal fue el caso del Río de la Plata, que además no ofrecía oro, plata o materias codiciables.

Se valoriza así la tarea llevada a cabo por quienes se internaron en sus márgenes, descubrieron su sistema hidrográfico, las tierras circundantes y fundaron ciudades.

Como en una novela de aventuras, provocarán admiración y sorpresa los trajines y desvelos de estos conquistadores que no desdeñaron -la mayoría lo hacía-, las regiones costeras, desafiaron el poder ofensivo de los indios de las planicies, resignados a la falta de metales preciosos, y fueron descendiendo a las tierras bajas e inhospitalarias, para hacerse de un dominio lo que, por entonces, se llamaba “descargar la tierra”.

Muchos sucumbieron en la empresa, pero la tierra pudo pagar con creces a la humanidad. Pocos siglos después, las pampas aledañas al Río de la Plata iban a ser conocidas como “el granero del mundo”.

**Ver**: [¿Qué sucedió en el mundo en estos años? (1480 / 1491)](http://descubrircorrientes.com.ar/2012/index.php/479-historia-desde-el-origen-hasta-1814/tierra-argentina-1492-1588/la-aventura-del-rio-de-la-plata/americo-vespucio-descubridor-del-rio-de-la-plata/la-monarquia-bicefala-de-los-reyes-catolicos/index.php?option=com_content&view=category&id=2477&Itemid=510)